version: '3.7'

services:

  mongo:
      container_name: mongodb-service
      image: mongo
      volumes:
        - ./host-data/mongo-data:/var/lib/mongodb
        - ./docker/mongo/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
        # - ./docker/mongo/mongod.conf:/etc/mongod.conf   USE FOR REPLICASET INSTALLATIONS
      healthcheck:
          test: test $$(echo "rs.initiate().ok || rs.status().ok" --quiet) -eq 1
          interval: 10s
          start_period: 30s
      # command: ["-f", "/etc/mongod.conf", "--replSet", "secluded", "--bind_ip_all"]    USE FOR REPLICASET INSTALLATIONS
      ports:
        - '27017:27017'
      restart: unless-stopped
  redis:
      container_name: redis-service
      build:
        context: ./docker/redis/
      privileged: true
      command: sh -c "./init.sh"
      # restart: unless-stopped
      ports:
        - '6379:6379'
      volumes:
        - ./host-data/redis-data:/data/redis:rw
